<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Начало работы</title>
    <link type="text/css" rel="stylesheet" href="/static/css/styleForFirstPage.css">
    <script src="/static/js/main.js"></script>
    <script>
        setTimeout(function () {
            window.location.href = '/index';
        }, /*Math.random() * */ 10 * 1000);
    </script>
</head>
<body>
<div class="wrap">
    <button class="button">Заходим</button>
</div>
</body>
</html>
