<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Начало работы</title>
    <link type="text/css" rel="stylesheet" href="/static/css/styleForFirstPage1.css">
    <script>
        setTimeout(function(){
            window.location.href = '/index';
        }, 10 * 1000);
    </script>
<#--<div>let's go!!!</div>-->
    <div class="wrap">
        <button class="button">Submit</button>
    </div>
</html>
